# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.x'
  condition: always()

- script: |
   pip install -r Requirements.txt
  displayName: 'Install Robot Dependencies'
  continueOnError: true
  condition: always()

- script: |
   npm install @puppeteer/browsers@latest
   npx @puppeteer/browsers install chrome@121.0.6167.86
   echo "##vso[task.prependpath]${Agent.ToolsDirectory}"
  
  displayName: 'Install Chrome'

- script: |
   npx @puppeteer/browsers install chromedriver@121.0.6167  --path  C:\Users\VssAdministrator\AppData\Roaming\Python\Python312\Scripts
   echo "##vso[task.prependpath]${Agent.ToolsDirectory}"
  displayName: 'Install Chrome Driver'
 
- powershell: |
   # Run the initial Robot Framework tests
   robot --outputdir results Tests/
   exit 0
  displayName: 'Run Robot Framework Tests'
  continueOnError: true
  condition: always()


- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
   targetPath: 'results'
   artifact: 'Robot Test Execution Results'
  continueOnError: true
  condition: always()


- task: SendGrid@1
  inputs:
    sendgridkey: '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'
    to: 'hridaybhogayata@gmail.com'
    from: 'hridaybhogayata4@gmail.com'
    subject: 'Azure CI Test Report by Send grid'
    htmlbody: |
      Hello,
            
      Please check the attached reports for Azure CI Automation pipeline run.
    addattachment: true
    attachment: 'D:\a\1\s\results\report.html'
  
  displayName: 'Send Email Notifications'
  condition: always()


