name: Publish Azure Report to GitHub Pages

on:
  workflow_dispatch: # Triggered manually or via REST API
  push:
    branches: [main] # Deploy when changes are pushed to the gh-pages branch

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: Robot Test Execution Results # Ensure you upload the artifact with this name in Azure Pipelines

      - name: Copy Report to Root
        run: |
          cp -R Robot Test Execution Results/report.html ./

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add report.html
          git commit -m "Update GitHub Pages with Azure Report"
          git push
